apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pg-upgrade
resources:
  - cluster.yaml
labels:
  - includeSelectors: false
    pairs:
      percona-pg-lab.io/profile: upgrade-demo
