#!/usr/bin/env python3
"""Turn a pgbench sweep CSV into docs/10-performance-results.md.

Kept deliberately dependency-free (stdlib only) so that `make perf` works on a
fresh checkout without a virtualenv.
"""
import csv
import platform
import subprocess
import sys
from collections import defaultdict
from datetime import datetime, timezone


def hardware() -> str:
    """Describe the machine, so nobody quotes these numbers as universal."""
    bits = [f"{platform.system()} {platform.machine()}"]
    try:
        info = subprocess.run(
            ["docker", "info", "--format", "{{.NCPU}} CPU / {{.MemTotal}}"],
            capture_output=True, text=True, timeout=10,
        ).stdout.strip()
        cpu, _, mem = info.partition(" CPU / ")
        if cpu and mem.isdigit():
            bits.append(f"Docker VM {cpu} CPU / {int(mem) / 1024**3:.1f} GiB")
    except Exception:
        pass
    return ", ".join(bits)


def main(path: str) -> None:
    with open(path, newline="") as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        sys.exit("no rows in sweep csv")

    # (mode, clients, rate) -> {target: row}
    grouped: dict[tuple, dict] = defaultdict(dict)
    for r in rows:
        grouped[(r["mode"], int(r["clients"]), int(r["rate"]))][r["target"]] = r

    duration = rows[0]["duration_s"]
    out = []
    w = out.append

    w("# Performance results")
    w("")
    w("<!-- GENERATED BY perf/report.py — edit perf/run-sweep.sh, not this file. -->")
    w("")
    w(f"Measured {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} "
      f"on {hardware()}, each run {duration}s, `pgbench` executed **inside** the "
      f"cluster against the `ha` profile.")
    w("")
    w("These numbers describe a four-node kind cluster on a laptop. Treat the "
      "*ratios* as transferable and the absolute values as not.")
    w("")
    w("**Expect run-to-run variance in the throughput columns.** A full sweep is "
      "~30 measurements back to back on shared hardware, and later runs are "
      "affected by what earlier ones left behind (cache state, WAL volume, "
      "autovacuum). Isolated repeats of a single row have produced tps figures "
      "2–3x higher than the same row inside a full sweep. The **backend counts** "
      "are stable and reproducible — and they are the point.")
    w("")
    w("## How to read this")
    w("")
    w("The `rate` column is what makes this table worth anything.")
    w("")
    w("- **rate = 0** — unlimited. Every client is inside a transaction at all "
      "times, so pgBouncer has nothing to multiplex: it needs roughly one "
      "backend per client, exactly like a direct connection, and the only thing "
      "it can contribute is one extra network hop. This is the shape that "
      "produces \"we benchmarked pgBouncer and it was slower\".")
    w("- **rate > 0** — clients are idle between transactions, which is what a "
      "real application connection pool looks like. Here pgBouncer hands one "
      "backend to many clients in turn, and the `backends` column collapses.")
    w("")
    w("`backends` is the peak count of `client backend` processes observed on "
      "the primary during the run. It is the number that decides whether you "
      "run out of `max_connections`, and the reason to deploy a pooler at all.")
    w("")

    notes = {
        "ro": None,
        "rw": ("These runs are **disk-bound on kind**, not pooling-bound. "
               "`local-path` volumes on a laptop, combined with "
               "`synchronous_commit: on` and a synchronous standby, dominate "
               "everything else — the numbers are two orders of magnitude below "
               "the read-only figures and the direct-vs-pooled difference is "
               "mostly noise. Included for completeness; draw conclusions about "
               "pooling from the read-only table."),
    }
    for mode, title in (("ro", "Read-only (`pgbench -S`)"),
                        ("rw", "Read-write (TPC-B like)")):
        keys = sorted(k for k in grouped if k[0] == mode)
        if not keys:
            continue
        w(f"## {title}")
        w("")
        if notes.get(mode):
            w(f"> {notes[mode]}")
            w("")
        w("| clients | rate | target | tps | latency (ms) | peak backends | backends vs clients |")
        w("|--------:|-----:|--------|----:|-------------:|--------------:|--------------------:|")
        for key in keys:
            _, clients, rate = key
            for target in ("direct", "pgbouncer"):
                r = grouped[key].get(target)
                if not r:
                    continue
                note = (r.get("note") or "").strip()
                if note:
                    # A failed run is a result, not a gap. The one that matters
                    # is "max_connections exceeded" on the direct target.
                    w(f"| {clients} | {rate or '∞'} | {target} | — | — | — | "
                      f"**{note}** |")
                    continue
                peak = int(r["peak_backends"])
                ratio = f"{peak / clients:.2f}x" if clients else "—"
                w(f"| {clients} | {rate or '∞'} | {target} | {r['tps']} | "
                  f"{r['latency_ms']} | {peak} | {ratio} |")
        w("")

    # Headline comparison: the rate-limited rows are the interesting ones.
    limited = [k for k in grouped if k[2] > 0 or
               any((g.get("note") or "").strip() for g in grouped[k].values())]
    if limited:
        w("## The short version")
        w("")
        for key in sorted(limited):
            g = grouped[key]
            if "direct" not in g or "pgbouncer" not in g:
                continue
            if (g["direct"].get("note") or "").strip():
                mode, clients, rate = key
                w(f"- **{clients} clients at {rate} tps ({mode})**: the direct "
                  f"connection **failed outright** "
                  f"(`{g['direct']['note']}`) while pgBouncer served it at "
                  f"{g['pgbouncer']['tps']} tps on "
                  f"{g['pgbouncer']['peak_backends']} backends.")
                continue
            if (g["pgbouncer"].get("note") or "").strip():
                continue
            d, p = int(g["direct"]["peak_backends"]), int(g["pgbouncer"]["peak_backends"])
            if p and d > p:
                mode, clients, rate = key
                w(f"- **{clients} clients at {rate} tps ({mode})**: "
                  f"{d} backends direct vs **{p}** through pgBouncer "
                  f"— a {d / p:.1f}x reduction, at "
                  f"{g['pgbouncer']['tps']} vs {g['direct']['tps']} tps.")
        w("")

    w("Reproduce with `make perf`. Raw CSVs land in `perf/results/`.")
    w("")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "perf/results/latest.csv")
